### ISSUE TITLE
Add unratified countries

### ISSUE THREAD

**Issue by louispotok** [openclimatedata/kigali-amendment-entry-into-force#1]
Hi, thanks for this great data source!

I think it would increase the value of this repository if the list included the names of countries that have not yet ratified the Kigali Amendment. To indicate that they haven't ratified, either the "date" column could be left blank or another "status" column could be added. 

This would solve potential problems around country names being inconsistent across sources.

For example, I have a [dataset](https://github.com/louispotok/green-cooling-data) of cooling-related emissions, but the names from my source can be different from what you have here (eg "Vietnam" vs "Viet Nam"). If you had all the names available now, then my data cleaning/mapping efforts to join these would only have to be done once -- instead of new efforts potentially being required when your list updated.

If there is not a canonical list from the UN of what all the country names they use are, perhaps you could use the list of countries that have ratified the Montreal Protocol as a base -- it wouldn't be fully comprehensive but would be a good step.

Let me know what you think, thanks!

**Comment by louispotok** [comment]
Looking through the code here I do see use of the `countrynames` library which might help with this (and it looks like some overlap in contributors!). But I do think the suggestion stands and would be valuable.

**Comment by rgieseke** [comment]
Exactly, that's what i'm using the `countrynames` library for, so that each party has their proper 3-letter code.
I think it's easier if you add a column with 3-letter codes to your table and merge or compare on these. 
Usually, i only keep the country name column for reference and rely on codes for joining datasets.

**Comment by rgieseke** [comment]
It's probably a rare event, but the number or name of countries could change and then i would have to keep track of UN countries somehow (though i sort-of do for some groups in https://github.com/openclimatedata/countrygroups)

**Comment by louispotok** [comment]
Completely agree that country codes are the way to go. On reflection, I'll close this issue. Thanks!

**Comment by rgieseke** [comment]
Thanks for raising it and glad this repo is useful to you (and glad that's GitHub's actions automatically update it ...)!
