### ISSUE TITLE
Re-enable weekly updates

### ISSUE THREAD

**Issue by louispotok** [openclimatedata/kigali-amendment-entry-into-force#6]
Hi @rgieseke !

It looks like the weekly updates haven't been running. On [this page](https://github.com/openclimatedata/kigali-amendment-entry-into-force/actions/workflows/update.yml) I see that GH automatically disables workflows any time 60 days go by without a commit, and you'll need to manually re-enable this. I did a bit of searching and unfortunately doesn't look like there's any way to modify this behavior.

![image](https://github.com/openclimatedata/kigali-amendment-entry-into-force/assets/5413548/08d0682e-8d29-49e1-9657-8c407406fcf1)

**Comment by rgieseke** [comment]
Good catch, thanks! I've run a manual update (adding Bahamas) and re-enabled the workflow.

**Comment by rgieseke** [comment]
A workaround could be to add a timestamp to a file or update the Readme with "Last update: [date]" after each successful weekly run (or once a month).

https://mastodon.social/@openclimatedata/110569935568766179
